server:
  port: 9001

spring:
  application:
    name: ADDRESS-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://serviceregistry.bc61.tk/eureka/
  instance:
    hostname: serviceregistry.bc61.tk
